### ISSUE TITLE
Issues with hooks in useStoryblok 

### ISSUE THREAD

**Issue by johannes-lindgren** [storyblok/storyblok-react#112]
There are a few issues with the `useStoryblok()`:

1. `useEffect()` is called conditionally on [line 40](https://github.com/storyblok/storyblok-react/blob/feature/v1/lib/index.ts#L40), caused by early return statement on [line 35](https://github.com/storyblok/storyblok-react/blob/feature/v1/lib/index.ts#L35). See the [rules of hooks](https://reactjs.org/docs/hooks-rules.html)
2. `useSbBridge()` causes side-effects, yet it is not called within `useEffect(). (Despite its name, useSbBridge is not a react hook)
3. `useStoryblokBridge()` cause side-effects that are not cleaned up. How do we prevent memory leaks? What if the registered events try to mutate the state of a component that has unmounted?
4. On [line 47](https://github.com/storyblok/storyblok-react/blob/feature/v1/lib/index.ts#L47), we might be mutating the component's state after it has unmounted. This will happen if the component is unmounted after sending the fetch request, and before the `setState()` is called. See https://www.codingdeft.com/posts/react-prevent-state-update-unmounted-component/
5. I am not completely sure about this one: In `useStoryblokBridge()`, we are subscribing to events from the bridge. If two different components are calling `useStoryblokBridge()`, then I assume that [line 37](https://github.com/storyblok/storyblok-js/blob/main/lib/index.ts#L37) will be called twice; one will pass the condition and result in a mutated state, and the other will cause the window to reload. That's a side-effect that is not easy to foresee. Since we are not cleaning up the event listeners (I think), anytime we unmount the story component and replace it with another story component, the window _will_ reload.

**Comment by bertrand-riviere** [comment]
i also think it is missleading to use the "useStoryblokBridge" inside storyblok-react lib because as far i can see it is simply a re-export from @storyblok/js which has nothing to do with React:
https://github.com/storyblok/storyblok-react/blob/56a8adf239f1bf8ceb4d7aa20aa3d474fb4146c3/lib/index.ts#L21

if a user directly uses it as if it was a React hook (at the root of the render func) the event will gets added again and again, render after render.

i think you should implement a proper React hook in this lib (wrapping the call to useStoryblokBridge in a useEffect with a callback dependencies, etc.. + do the needed cleaning up as [johannes-lindgren](https://github.com/johannes-lindgren) mentionned) or at least you should make it very clear in the doc that useStoryblokBridge is NOT a hook as its name suggests.

**Comment by CAYdenberg** [comment]
I have a similar issue with `useStoryblokState` which is causing my previews to crash.

This `useEffect` (https://github.com/storyblok/storyblok-react/blob/60cd8de274b0031bb9ae59e131008a5851e76b7f/lib/common/client.ts#L22) is called conditionally.

I would really suggest using React's eslint plugin to enforce the Rules of Hooks.

**Comment by yannic-wtfoxtrot** [comment]
I think the first issue is the most annoying as it causes the following error with each HMR update: `Error: Rendered more hooks than during the previous render.`

I just noticed it in my Next js application and found it pretty hard to narrow down. From my understanding this could be easily resolved by moving the conditional to the `useEffect` itself. I'm going to create a PR and would greatly appreciate feedback here :)

**Comment by yannic-wtfoxtrot** [comment]
I just created a PR for this https://github.com/storyblok/storyblok-react/pull/870. I'd appreciate if someone could have a look at it :)

**Comment by whlufisc** [comment]
Hello 👋!  
Unfortunately PR https://github.com/storyblok/storyblok-react/pull/870 breaks the `useStoryblokState` hook.

Right now the `useEffect` hook is executed everytime `story` changes.
Now the following happens if the callback `(newStory) => setStory(newStory)` is executed:
1. Triggers a rerender -> `story` returned by `useState`
2. Effect is executed again
3. `setStory(initialStory);` resets the state variable back to its initial value
4. Another rerender is triggered with the old `initialStory` being returned by `useState`

When trying to edit something this can be observed in the live editor by content jumping around when something is changed, because the change is only displayed for one render.

This can be solved by pulling `const id = (story as any).internalId || story.id` back out of the `useEffect`-hook and using it as a dependency of the effect.
```typescript
const useStoryblokState: TUseStoryblokState = (initialStory = null, bridgeOptions = {}) => {
    const [story, setStory] = useState(initialStory)

    const isBridgeEnable = typeof window !== 'undefined' && typeof window.storyblokRegisterEvent !== 'undefined'
    const id = (story as any).internalId || story.id

    useEffect(() => {
        if (!isBridgeEnable || !initialStory) return
        setStory(initialStory)
        registerStoryblokBridge(id, (newStory) => setStory(newStory), bridgeOptions)
    }, [initialStory, isBridgeEnable, id])

    if (!isBridgeEnable || !initialStory) {
        return initialStory
    }

    return story
}
```

If you would want to adhere to the rules of hooks completely, including exhaustive-deps, you would have to include `bridgeOptions` as a dependency of the effect. But I would not recommend this because this object will not be stable when this is overriden by the user. 

Overall I don't think it is necessary here to be that strict with the dependencies in general. The function `registerStoryblokBridge` comes from another repo, so you will always have to make sure what happens if this function is called multiple times because of rerenders or you make sure that it is actually only called once.

**Comment by yannic-wtfoxtrot** [comment]
@whlufisc sounds good to me. Can you prepare a pull request?

**Comment by whlufisc** [comment]
Someone else was faster https://github.com/storyblok/storyblok-react/pull/883

**Comment by franzi-wtfoxtrot** [comment]
Hello, is there anyone who could do a review of the PR https://github.com/storyblok/storyblok-react/pull/883 ? The non-functioning preview is unsettling our editors and annoying us, as we cannot provide any other solution to the problem at the moment.

**Comment by arorachakit** [comment]
Hey @franzi-wtfoxtrot @whlufisc  - The PR was merged a couple of weeks back :) 

Maybe we can close this issue now @johannes-lindgren ?
