### ISSUE TITLE
storyblok-bridge-v2 compatibility issues

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok-react#18]
Hello

I am not sure if this is the package works directly with v2 storyblok bridge. I just dropped in the update and now the outlines are jumping around and the user experience is far away from ideal.

Are there any changes to be made?
Thanks

**Comment by fgiuliani** [comment]
Hey @dohomi have you tested this lately? We just released a new package:

https://www.npmjs.com/package/@storyblok/react

**Comment by dohomi** [comment]
@fgiuliani looking at the update I dislike the fact that the `storyblokInit ` function needs all components, why is that so? I have over 50 components I would need to import and all of them are code-splitted dynamically on demand.

**Comment by dohomi** [comment]
@fgiuliani I am using the DynamicComponent approach for my website at the moment. But what I am doing is having code-splitting enabled through [dynamic](https://nextjs.org/docs/advanced-features/dynamic-import) code splitting via NextJS. Will that be available with the `StoryblokComponent`? Is it necessary that all components will be imported in the `storyblokInit` part?

I am currently not able to try out this new approach, especially due to missing TypeScript support.

**Comment by fgiuliani** [comment]
@dohomi thanks for sharing!

Your scenario sounds interesting. Could you share more details, or a code sample, on how you are using the DynamicComponent approach? So we can see if we can handle your scenario.

Our idea was to add support for dynamic imports on the component list that is sent as a parameter for `storyblokInit` function.

Just to double-check and be clear, since the discussion took another path 😅: Does the issue that was originally reported [here](https://github.com/storyblok/storyblok-react/issues/18#issue-859365164) still make sense? Or since we are working on a new SDK, it doesn't apply anymore?

**Comment by dohomi** [comment]
@fgiuliani Instead of importing the component and use it right away I wrap them with `dynamic` like follow:
```ts
CoreComponents.table = dynamic(
  () => import(/* webpackChunkName: 'table' */ './table/Table')
)

CoreComponents.section_video_bg = dynamic(
  () => import(/* webpackChunkName: 'video' */ './section/SectionVideoBg')
)
```

I think the original compatibility issue might fixed already

**Comment by fgiuliani** [comment]
Hey @dohomi thanks for sharing these details. I will keep your comments in mind and discuss them with the team. We could work on the SDK so we can support components to be added following the approach you are using. We were already discussing how to dynamically import components.

In the meantime, I can tell you that the `components` section is not mandatory for the `storyblokInit` function. So, you can keep using the approach that you have for the dynamic components in your solution, you don't need to list all the components when calling `storyblokInit`.

How does it sound?

Again, thank you for your feedback. I would say that we can close this issue since the original problem was fixed, what do you think? Feel free to create a new one about the dynamic imports, or in case you find any other problem in the new SDK.

**Comment by dohomi** [comment]
@fgiuliani sure I will keep an eye open :-)
