### ISSUE TITLE
this.throttle takes { paramsSerializer: as a prop of third argument, which leads to AxiosError: BAD_OPTION_VALUE: options is not an object

### ISSUE THREAD

**Issue by Redskinsjo** [storyblok/storyblok-react#286]
Hi,
I just encountered an error with this prop, that leads to an AxiosError: BAD_OPTION_VALUE: options is not an object. file axios/lib/helpers/validator.js function AssertOptions.
"@storyblok/react": "^1.3.3"
"axios": "^1.1.3"

paramsSerializer is given a function: (e) => a(e)
To solve the issue, I gave him an empty object: {} instead.

Is my solution a regression, how do you suggest to solve this issue

weird error that happened because once it was working well and suddenly fell into this

**Comment by christophby** [comment]
+1

**Comment by fgiuliani** [comment]
Hey @christophby @Redskinsjo we're working on a change for the React SDK that will solve this issue since we will remove the `axios` dependency from the `storyblok-js-client`.
Will keep you updated about that

**Comment by guanacone** [comment]
getting a similar issue when using `sbStory = useStoryblok(story.slug, { version: 'draft', language: locale });` I'm getting an error: `Unhandled Runtime Error AxiosError: options must be an object`

**Comment by fgiuliani** [comment]
Hello everyone!
We just released Storyblok React SDK v2.0.0:
https://github.com/storyblok/storyblok-react/releases/tag/v2.0.0

With this PR we're removing the `axios` dependency. You don't need to install it anymore in order to use the Storyblok React SDK:
https://github.com/storyblok/storyblok-react/pull/345

For that reason, this issue should be fixed now. 
Let us know if this works for you.
