### ISSUE TITLE
AxiosError: options must be an object

### ISSUE THREAD

**Issue by mrphemi** [storyblok/storyblok-react#333]
## Expected Behavior

I'm currently following the tutorial on how to integrate storyblok on a Next.js project on the [storyblok](https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-in-5-minutes) website. I expect everything to work as explained in the tutorial.

## Current Behavior

I am at [this point](https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-in-5-minutes#fetching-data) of the tutorial and I am getting an error that I think stems from `axios`. The image and codeblock below describes the details of the error.

<img width="955" alt="Screenshot 2022-12-06 at 16 21 04" src="https://user-images.githubusercontent.com/26447097/205956869-1e62cde3-73fd-4fb4-8617-b5403c88d753.png">

<img width="1095" alt="Screenshot 2022-12-06 at 16 59 50" src="https://user-images.githubusercontent.com/26447097/205961146-dbee6b49-fa9c-498c-ad94-ba188f80eaee.png">

## Steps to Reproduce

1. Spin up a Next.js project using [create-next-app](https://nextjs.org/docs/api-reference/create-next-app).
2.  Install the latest version of `@storyblok/react` and  `axios`.
3. Follow [this](https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-in-5-minutes) tutorial on the storyblok website until you get to this [section] (https://www.storyblok.com/tp/add-a-headless-cms-to-next-js-in-5-minutes#fetching-data).

I'm on

- Node.js v18.12.1
- Npm v8.19.2
- @storyblok/react": "^1.3.4
- axios: "^1.2.1

**Comment by fgiuliani** [comment]
hey @mrphemi a very similar issue was reported here:
https://github.com/storyblok/storyblok-react/issues/286

As I mentioned in this comment:
https://github.com/storyblok/storyblok-react/issues/286#issuecomment-1315565582

We're working on a change for the React SDK that will solve this issue since we will remove the axios dependency from the `storyblok-js-client`.

**Comment by guanacone** [comment]
> We're working on a change for the React SDK that will solve this issue since we will remove the axios dependency from the `storyblok-js-client`.

Any estimate on how long this will this take? [#286](https://github.com/storyblok/storyblok-react/issues/286) is open sinc the 25th of October?

**Comment by fgiuliani** [comment]
Hey @guanacone we're working to have a new React SDK version, removing `axios` dependency, before the year ends

**Comment by fgiuliani** [comment]
Hello everyone!
We just released Storyblok React SDK v2.0.0:
https://github.com/storyblok/storyblok-react/releases/tag/v2.0.0

With this PR we're removing the `axios` dependency. You don't need to install it anymore in order to use the Storyblok React SDK:
https://github.com/storyblok/storyblok-react/pull/345

For that reason, this issue should be fixed now. 
Let us know if this works for you.
