### ISSUE TITLE
Some pages in storyblok are not getting called when clicked on button

### ISSUE THREAD

**Issue by bhavesh-chundru** [storyblok/storyblok-react#346]
I have been using @storyblok/react and react-router-dom to navigate through pages to serve the spa as we are using redux and i dont want my state to be cleared while navigating to next page/screen for some pages it is getting triggered and api call is happening and story is loaded components are rendered,for some it doesn't, although in the url of the page changes but storyblok api call is not happening .I faced this issue in the beginning and later this was working fine and showed up now I am not sure for which other pages the same issue might occur. Can i have quick solution for this please 

if you see in the below image when I clicked on the my-bookings in the bottombar url has been changed but i am still in the homepage
<img width="959" alt="image" src="https://user-images.githubusercontent.com/99734165/207733906-42234de8-db40-43cf-93ba-c178141b2500.png">

**Comment by fgiuliani** [comment]
Hi @bhavesh-chundru,
We just released Storyblok React SDK v2.0.0:
https://github.com/storyblok/storyblok-react/releases/tag/v2.0.0

With this PR we're removing the `axios` dependency. You don't need to install it anymore in order to use the Storyblok React SDK.
We are also adding other changes and fixes:
https://github.com/storyblok/storyblok-react/pull/345

Your feedback is appreciated
